### ISSUE TITLE
Getting Eslint error for import/no-extraneous-dependencies

### ISSUE THREAD

**Issue by ghost** [vercel/style-guide#81]
✖ eslint --fix:

Oops! Something went wrong! :(

ESLint: 8.54.0

Error: packages\ui\.eslintrc.js » eslint-config-custom/react » \node_modules\@vercel\style-guide\eslint\browser.js » \node_modules\@vercel\style-guide\eslint\_base.js »\node_modules\@vercel\style-guide\eslint\rules\import.js:
        Configuration for rule "import/no-extraneous-dependencies" is invalid:
        Value {"includeTypes":true} should NOT have additional properties.

    at ConfigValidator.validateRuleOptions (\node_modules\@eslint\eslintrc\dist\eslintrc.cjs:2039:23)
    at \node_modules\@eslint\eslintrc\dist\eslintrc.cjs:2094:18
    at Array.forEach (<anonymous>)
    at ConfigValidator.validateRules (\node_modules\@eslint\eslintrc\dist\eslintrc.cjs:2091:34)
    at ConfigValidator.validateConfigArray (\node_modules\@eslint\eslintrc\dist\eslintrc.cjs:2217:18)
    at CascadingConfigArrayFactory._finalizeConfigArray (\node_modules\@eslint\eslintrc\dist\eslintrc.cjs:3974:23)
    at CascadingConfigArrayFactory.getConfigArrayForFile (]\node_modules\@eslint\eslintrc\dist\eslintrc.cjs:3780:21)
    at FileEnumerator._iterateFilesWithFile (\node_modules\eslint\lib\cli-engine\file-enumerator.js:368:43)
    at FileEnumerator._iterateFiles (\node_modules\eslint\lib\cli-engine\file-enumerator.js:349:25)
    at FileEnumerator.iterateFiles (\node_modules\eslint\lib\cli-engine\file-enumerator.js:299:59)
husky - pre-commit hook exited with code 1 (error)

**Comment by mrmckeb** [comment]
Hi @nikhilsnayak, is it possible that you have a version mismatch? Do you have `eslint-plugin-import` installed locally at an older version?

The just double checked that the configuration is correct, and we're using this internally.
https://github.com/import-js/eslint-plugin-import/blob/main/docs/rules/no-extraneous-dependencies.md

**Comment by mrmckeb** [comment]
Closing this as stale.
